var _cl = camera_get_view_width(view_camera[0]);
var _ca = camera_get_view_height(view_camera[0]);
escalaX = display_get_gui_width() / _cl;
escalaY = display_get_gui_height() / _ca;
dano = -1;
alvo = -1;
xx = alvo.x;
yy = alvo.y;
alpha = 1;
